### Project Group ###
projectGroup=com.loopers
### Project dependency versions ###
kotlinVersion=2.3.21
### Plugin dependency versions ###
ktLintPluginVersion=14.2.0
ktLintVersion=1.8.0
### Spring dependency versions ###
springBootVersion=4.1.1
springDependencyManagementVersion=1.1.7
### Library versions ###
springDocOpenApiVersion=3.1.1
springMockkVersion=4.0.2
mockitoVersion=5.14.0
mockitoKotlinVersion=5.4.0
instancioJUnitVersion=6.1.0
archUnitVersion=1.5.1
slackAppenderVersion=1.6.1
kotlinLoggingVersion=8.0.4
kotlin.daemon.jvmargs=-Xmx1g -XX:MaxMetaspaceSize=512m
